server:
  port: 9000

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://muscat.czwt78mf7f1j.ap-northeast-2.rds.amazonaws.com:3306/muscat?useSSL=false
    username: admin
    password: qlqjs0spro


  mail:
    host: smtp.gmail.com
    port: 587
    username: 'cs@tivansoft.com'
    password: 'eyktcwfixlwpajqh'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    jdbc.sqlonly: debug
    jdbc.audit: off
    jdbc.connection: off
    jdbc.resultset: off
    jdbc.resultsettable: debug
    jdbc.sqltiming: off
